### ISSUE TITLE
Invalid game configuration file throws exceptions instead of logging syntax errors

### ISSUE THREAD

**Issue by ioan-chera** [m-x-d/GZDoom-Builder#3]
I'm trying to update this Eternity configuration file (Eternity_linedefs.cfg) and I probably have errors in it, but I'm unable to see them because GZDB throws exceptions (such as the generic NullReferenceException) instead of displaying accurate error messages.

I'm posting this (possibly wrong) .cfg file so you can debug the cause of the exceptions by using it.

[Eternity_linedefs.cfg.txt](https://github.com/m-x-d/GZDoom-Builder/files/691583/Eternity_linedefs.cfg.txt)

**Comment by m-x-d** [comment]
Fixed by adding boilerplate. When overriding an existing linedef properties, the new definition must be in the same category as the original one. In your case, action 74 must be in the "teleport" category in Eternity_linedefs.cfg.
